name: CocoaPods Action

on:
- pull_request

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.6.app
    - name: Install Dependencies
      run: |
        cd CatVoter
        pod repo update
        pod install
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        workspace: CatVoter.xcworkspace
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.6'
        lint: false